---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: default
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: OnFailure
          hostNetwork: true
          # use nodeSelector and tolerations to schedule the pod on master node
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
          serviceAccountName: etcd-backup
          dnsPolicy: ClusterFirst
          volumes:
            - hostPath:
                path: /
                type: Directory
              name: host
            - name: shh-key
              secret:
                defaultMode: 384      # permission mode 0600
                secretName: ssh-key
            - name: backup-script
              configMap:
                defaultMode: 360      # permission mode 0500
                name: backup-script
          containers:
            - name: etcd-backup
              image: registry.redhat.io/rhel-minimal:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: BACKUP_PATH
                  value: /opt/etcd-backup/cluster
              command:
                - /bin/sh
                - -c
                - /etcd-backup/etcd-backup.sh
              resources:
                requests:
                  cpu: 500m
                  memory: 128Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
              securityContext:
                privileged: true
                runAsUser: 0
              volumeMounts:
                - name: host
                  mountPath: /host
                - name: shh-key
                  mountPath: /etcd-backup/ssh-rsa-key
                  subPath: ssh-rsa-key
                - name: backup-script
                  mountPath: /etcd-backup/etcd-backup.sh
                  subPath: etcd-backup.sh
...
