apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etcd-backup

generatorOptions:
  disableNameSuffixHash: true

resources:
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - cronjob.yaml

# secretGenerator:
# - name: private-ca
#   files:
#   - ca.pem
