apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etcd-backup

generatorOptions:
  disableNameSuffixHash: true

resources:
  - rbac.yaml
  - cronjob.yaml

configMapGenerator:
- name: backup-script
  files:
  - etcd-backup.sh

secretGenerator:
- name: ssh-key
  files:
  - ssh-key
