---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup
  # labels:
  #   app: etcd
  #   component: backup

---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: use-privileged-scc
# rules:
#   - apiGroups:
#       - security.openshift.io
#     resources:
#       - securitycontextconstraints
#     verbs:
#       - use
#     resourceNames:
#       - privileged

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-backup-sa-privileged
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: etcd-backup
    namespace: default
