---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-backup-sa-privileged
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: etcd-backup
    namespace: default
...
