---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etcd-backup
              env:
                - name: BACKUP_PATH
                  value: /opt/etcd-backup/dev-cluster
                # the values for the following environment variables are default in the script, no need to explicitly set
                # only need to explicitly set environment variable if using non-default value
                # - name: SFTP_SERVER
                #   value: 10.66.202.107
                # - name: SFTP_PORT
                #   value: "-P 22"
                # - name: SFTP_USERNAME
                #   value: "etcd-backup"
                # - name: SSH_OPTIONS
                #   value: "-o StrictHostKeyChecking=no"
...
