# ansible-playbook openshift-agent-install-config.yaml -e cluster_config=cluster-config.yaml
#
# expects these additional extra_vars:
#   cluster_config - yaml config file for the cluster
#
---
- name: create config files for agent based openshift installer
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: assert that cluster config file is provided
      ansible.builtin.assert:
        that:
          - cluster_config is defined
          - cluster_config != ""
        fail_msg: "cluster_config variable is not set; please run ansible-playbook with '-e cluster_config=<path-to-cluster-config-yaml-file>' option"
        success_msg: "cluster config yaml file provided"

    - name: create custom coreos live iso image
      vars:
        _config: "{{ lookup('ansible.builtin.file', cluster_config) | from_yaml }}"
      ansible.builtin.include_role:
        name: openshift-install-config
...
