apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
 - target:
      group: batch
      version: v1
      kind: CronJob
      name: etcd-backup
   path: cronjob-patch.yaml
